CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY,
  username varchar(64) NOT NULL UNIQUE,
  email varchar(255) UNIQUE,
  password_hash varchar(255) NOT NULL,
  display_name varchar(120) NOT NULL,
  email_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pages (
  id uuid PRIMARY KEY,
  owner_user_id uuid NOT NULL REFERENCES users(id),
  title varchar(200) NOT NULL,
  visibility varchar(32) NOT NULL DEFAULT 'public',
  status varchar(32) NOT NULL DEFAULT 'generating',
  current_version_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_pages_visibility CHECK (visibility IN ('private', 'restricted', 'public')),
  CONSTRAINT chk_pages_status CHECK (status IN ('generating', 'ready', 'failed', 'suspended', 'deleted'))
);

CREATE TABLE IF NOT EXISTS page_versions (
  id uuid PRIMARY KEY,
  page_id uuid NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  version_number integer NOT NULL,
  prompt text NOT NULL,
  storage_key varchar(512) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'ready',
  model_provider varchar(64),
  model_name varchar(128),
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_page_versions_page_number UNIQUE (page_id, version_number),
  CONSTRAINT chk_page_versions_status CHECK (status IN ('generating', 'ready', 'failed', 'archived'))
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_pages_current_version_id'
  ) THEN
    ALTER TABLE pages
      ADD CONSTRAINT fk_pages_current_version_id
      FOREIGN KEY (current_version_id) REFERENCES page_versions(id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS page_permissions (
  id uuid PRIMARY KEY,
  page_id uuid NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_page_permissions_page_user UNIQUE (page_id, user_id),
  CONSTRAINT chk_page_permissions_role CHECK (role IN ('owner', 'viewer', 'editor'))
);

CREATE TABLE IF NOT EXISTS generation_tasks (
  id uuid PRIMARY KEY,
  page_id uuid NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  requested_by_user_id uuid NOT NULL REFERENCES users(id),
  prompt text NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'pending',
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz,
  CONSTRAINT chk_generation_tasks_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS generation_events (
  id uuid PRIMARY KEY,
  task_id uuid NOT NULL REFERENCES generation_tasks(id) ON DELETE CASCADE,
  sequence integer GENERATED BY DEFAULT AS IDENTITY,
  event_type varchar(64) NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_generation_events_task_sequence UNIQUE (task_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_pages_owner ON pages(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_page_versions_page ON page_versions(page_id);
CREATE INDEX IF NOT EXISTS idx_generation_tasks_status ON generation_tasks(status);
CREATE INDEX IF NOT EXISTS idx_generation_events_task_sequence ON generation_events(task_id, sequence);
